require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Admin::StaffcommentsController do

  # This should return the minimal set of attributes required to create a valid
  # Admin::Staffcomment. As you add validations to Admin::Staffcomment, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Admin::StaffcommentsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all admin_staffcomments as @admin_staffcomments" do
      staffcomment = Admin::Staffcomment.create! valid_attributes
      get :index, {}, valid_session
      assigns(:admin_staffcomments).should eq([staffcomment])
    end
  end

  describe "GET show" do
    it "assigns the requested admin_staffcomment as @admin_staffcomment" do
      staffcomment = Admin::Staffcomment.create! valid_attributes
      get :show, {:id => staffcomment.to_param}, valid_session
      assigns(:admin_staffcomment).should eq(staffcomment)
    end
  end

  describe "GET new" do
    it "assigns a new admin_staffcomment as @admin_staffcomment" do
      get :new, {}, valid_session
      assigns(:admin_staffcomment).should be_a_new(Admin::Staffcomment)
    end
  end

  describe "GET edit" do
    it "assigns the requested admin_staffcomment as @admin_staffcomment" do
      staffcomment = Admin::Staffcomment.create! valid_attributes
      get :edit, {:id => staffcomment.to_param}, valid_session
      assigns(:admin_staffcomment).should eq(staffcomment)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Admin::Staffcomment" do
        expect {
          post :create, {:admin_staffcomment => valid_attributes}, valid_session
        }.to change(Admin::Staffcomment, :count).by(1)
      end

      it "assigns a newly created admin_staffcomment as @admin_staffcomment" do
        post :create, {:admin_staffcomment => valid_attributes}, valid_session
        assigns(:admin_staffcomment).should be_a(Admin::Staffcomment)
        assigns(:admin_staffcomment).should be_persisted
      end

      it "redirects to the created admin_staffcomment" do
        post :create, {:admin_staffcomment => valid_attributes}, valid_session
        response.should redirect_to(Admin::Staffcomment.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved admin_staffcomment as @admin_staffcomment" do
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::Staffcomment.any_instance.stub(:save).and_return(false)
        post :create, {:admin_staffcomment => {  }}, valid_session
        assigns(:admin_staffcomment).should be_a_new(Admin::Staffcomment)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::Staffcomment.any_instance.stub(:save).and_return(false)
        post :create, {:admin_staffcomment => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested admin_staffcomment" do
        staffcomment = Admin::Staffcomment.create! valid_attributes
        # Assuming there are no other admin_staffcomments in the database, this
        # specifies that the Admin::Staffcomment created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Admin::Staffcomment.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
        put :update, {:id => staffcomment.to_param, :admin_staffcomment => { "these" => "params" }}, valid_session
      end

      it "assigns the requested admin_staffcomment as @admin_staffcomment" do
        staffcomment = Admin::Staffcomment.create! valid_attributes
        put :update, {:id => staffcomment.to_param, :admin_staffcomment => valid_attributes}, valid_session
        assigns(:admin_staffcomment).should eq(staffcomment)
      end

      it "redirects to the admin_staffcomment" do
        staffcomment = Admin::Staffcomment.create! valid_attributes
        put :update, {:id => staffcomment.to_param, :admin_staffcomment => valid_attributes}, valid_session
        response.should redirect_to(staffcomment)
      end
    end

    describe "with invalid params" do
      it "assigns the admin_staffcomment as @admin_staffcomment" do
        staffcomment = Admin::Staffcomment.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::Staffcomment.any_instance.stub(:save).and_return(false)
        put :update, {:id => staffcomment.to_param, :admin_staffcomment => {  }}, valid_session
        assigns(:admin_staffcomment).should eq(staffcomment)
      end

      it "re-renders the 'edit' template" do
        staffcomment = Admin::Staffcomment.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::Staffcomment.any_instance.stub(:save).and_return(false)
        put :update, {:id => staffcomment.to_param, :admin_staffcomment => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested admin_staffcomment" do
      staffcomment = Admin::Staffcomment.create! valid_attributes
      expect {
        delete :destroy, {:id => staffcomment.to_param}, valid_session
      }.to change(Admin::Staffcomment, :count).by(-1)
    end

    it "redirects to the admin_staffcomments list" do
      staffcomment = Admin::Staffcomment.create! valid_attributes
      delete :destroy, {:id => staffcomment.to_param}, valid_session
      response.should redirect_to(admin_staffcomments_url)
    end
  end

end
